services:
  auth-service:
    image: ditoo2/geo-authservice:latest
    container_name: AuthService
    ports:
      - "8080:8080"
    environment:
      - Spring_Datasource_Url=jdbc:postgresql://ep-shrill-cherry-a8kycf0v-pooler.eastus2.azure.neon.tech/RadioAuthDB?sslmode=require&channelBinding=require
      - Spring_Datasource_Username=Ditoo2
      - Spring_Datasource_Password=npg_CpG6mKYlTd0o
    networks:
      - backend-network

  radio-management-service:
    image: ditoo2/geo-radioservice:latest
    container_name: RadioManagementService
    ports:
      - "8081:8081"
    networks:
      - backend-network

  radio-simulator:
    build:
      context: ./Radio Simulator
    container_name: RadioSimulator
    ports:
      - "80:80"
      - "81:81"
    environment:
      - DATABASE_URL=postgresql://Ditoo2:npg_CpG6mKYlTd0o@ep-shrill-cherry-a8kycf0v-pooler.eastus2.azure.neon.tech/RadioAuthDB?sslmode=require&channelBinding=require
    networks:
      - backend-network

  api-gateway:
    build:
      context: ./Backend/ApiGateway
    container_name: ApiGateway
    ports:
      - "8083:8080"
    depends_on:
      - auth-service
      - radio-management-service
      - radio-simulator
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
