services:
  auth-service:
    image: ditoo2/geo-authservice:latest
    container_name: AuthService
    ports:
      - "8080:8080"
    environment:
      - Spring_Datasource_Url=jdbc:postgresql://ep-shrill-cherry-a8kycf0v-pooler.eastus2.azure.neon.tech/RadioAuthDB?sslmode=require&channelBinding=require
      - Spring_Datasource_Username=Ditoo2
      - Spring_Datasource_Password=npg_CpG6mKYlTd0o
    networks:
      - backend-network

  notification-service:
    image: ditoo2/geo-notificationservice:latest
    container_name: NotificationService
    ports:
      - "8082:8082"
    networks:
      - backend-network

  radio-management-service:
    image: ditoo2/geo-radioservice:latest
    container_name: RadioManagementService
    ports:
      - "8081:8081"
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
