spring.application.name=AuthService
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${Spring_Datasource_Url}
spring.datasource.username=${Spring_Datasource_Username}
spring.datasource.password=${Spring_Datasource_Password}
spring.jpa.properties.hibernate.jdbc.timeout=60

jwt.secret=SGVsbG8gV29ybGQhSGVsbG8gV29ybGQhSGVsbG8gV29ybGQhSGVsbG8gV29ybGQhSGVsbG8gV29ybGQhSGVsbG8gV29ybGQhSGVsbG8gV29ybGQhSGVsbG8gV29ybGQ=

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
