spring.application.name=AuthService

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${Spring_Datasource_Url}
spring.datasource.username=${Spring_Datasource_Username}
spring.datasource.password=${Spring_Datasource_Password}
spring.jpa.properties.hibernate.jdbc.timeout=60
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.service.jta.platform.internal.NoJtaPlatform

